import { Role } from './roles.enum';

export const techStackByRole: { [key in Role]: TechStack[] } = {
  'AI Engineer': ['Python'],
  'Backend Engineer': [],
  'Frontend Engineer': [],
  'Fullstack Engineer': [],
  'Product Manager': [],
  'QA Engineer': [],
  'UX/UI Designer': [],
};

export const techStack = [
  '.NET',
  'Adobe XD',
  'Agile Methodologies',
  'Angular',
  'Astro',
  'AWS',
  'C#',
  'C / C++',
  'Chat GPT',
  'CI/CD',
  'Claude 3.5 Sonnet',
  'ClickUp',
  'Cypress',
  'Docker',
  'Express',
  'Expo',
  'FastAPI',
  'Figma',
  'Firebase',
  'Flask',
  'Flutter',
  'Framer Motion',
  'Go',
  'Hugging Face',
  'JavaScript',
  'Jira',
  'Kubernetes',
  'Laravel',
  'Linear',
  'MongoDB',
  'MySQL',
  'NestJS',
  'Next.js',
  'Node.js',
  'OpenCV',
  'Playwright',
  'PostgreSQL',
  'Posthog',
  'Prisma',
  'Python',
  'React',
  'React Native',
  'Redis',
  'Redux',
  'Ruby on Rails',
  'Rust',
  'Selenium',
  'Sentry',
  'Stripe',
  'Tailwind CSS',
  'TensorFlow',
  'Terraform',
  'tRPC',
  'TypeOrm',
  'TypeScript',
  'Vite',
  'Vue',
] as const;
export type TechStack = (typeof techStack)[number];
